name: Hugin CLI Main Pipeline

env:
  GITHUB_REGISTRY: "ghcr.io"
  GITHUB_OWNER: "mjovanc"
  GITHUB_DOCKER_IMAGE: "hugin-cli"
  BUILD_TYPE: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.architecture }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
              name: "Ubuntu Latest GCC",
              artifact: "hugin-ubuntu-x64",
              os: ubuntu-22.04,
              cc: "gcc",
              architecture: x64,
            }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Ubuntu 22.04
      - name: Install dependencies
        if: matrix.config.name == 'Ubuntu Latest GCC'
        run: sudo apt-get -y install libssl-dev libsqlcipher-dev

      - name: Build Ubuntu Target
        if: matrix.config.name == 'Ubuntu Latest GCC'
        run: make

      - name: Upload Ubuntu Artifact
        if: matrix.config.name == 'Ubuntu Latest GCC'
        uses: actions/upload-artifact@v3
        with:
          name: hugin-ubuntu-x64
          path: |
            build/Hugin
            resources/icon.png
            resources/readme.html
            resources/hugin-cli.desktop
            install.sh
