name: Hugin CLI Pull Request Pipeline

env:
  BUILD_TYPE: Debug

on: [ pull_request ]

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.architecture }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: true
      matrix:
        config:
          - {
            name: "Ubuntu Latest GCC",
            os: ubuntu-22.04,
            cc: "gcc",
            architecture: x64,
          }
          - {
            name: "macOS M1 Latest Clang",
            os: macos-12.0,
            cc: "clang",
            architecture: arm64,
          }
          - {
            name: "macOS Latest Clang",
            os: macos-12.0,
            cc: "clang",
            architecture: x64,
          }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Ubuntu
      - name: Install dependencies
        if: matrix.config.os == 'ubuntu-22.04'
        run: sudo apt-get -y install libssl-dev

      - name: Build Ubuntu Target
        if: matrix.config.os == 'ubuntu-22.04'
        run: make

      # macOS M1
      - name: Install dependencies
        if: matrix.config.os == 'macos-12.0' && matrix.config.architecture == 'arm64'
        run: brew install openssl@1.1

      - name: Build macOS M1 Target
        if: matrix.config.os == 'macos-12.0' && matrix.config.architecture == 'arm64'
        run: make

      # macOS 64-bit
      - name: Install dependencies
        if: matrix.config.os == 'macos-12.0' && matrix.config.architecture == 'x64'
        run: brew install openssl@1.1

      - name: Build macOS 64-bit Target
        if: matrix.config.os == 'macos-12.0' && matrix.config.architecture == 'x64'
        run: make
